import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/page";

export const metadata: Metadata = {
  title: "실시간 대중교통 정보",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Navbar />
      </body>
    </html>
  );
}
